name: 'fe : build'

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
  pull_request:
    branches: ['main']
    paths:
      - 'fe/**'
  push:
    branches: ['main']
    paths:
      - 'fe/**'

jobs:
  build-fe:
    name: fe-${{ inputs.env || 'stg' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .makefiles
            config.json
            Makefile
            fe
      - name: Build frontend
        run: make fe-build ENV=${{ inputs.env || 'stg' }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fe
          path: fe/dist
