name: 'fe : deploy'

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  deploy-fe:
    name: fe-${{ inputs.env }}
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .makefiles
            config.json
            Makefile
            fe
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fe
          path: fe/dist
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: deploy-fe
          role-to-assume: ${{ vars.AWS_ROLE }}
      - name: Deploy frontend
        run: make fe-deploy ENV=${{ inputs.env }}
