name: 'infra : test'

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
    paths:
      - 'infra/**'
  push:
    branches: ['main']
    paths:
      - 'infra/**'

env:
  SAM_CLI_TELEMETRY: 0

jobs:
  test-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .makefiles
            config.json
            Makefile
            infra
      - name: Run tests
        run: make infra-test
