name: 'setup-repo'

permissions:
  id-token: write
  contents: read
  
on:
  workflow_dispatch:
  fork:

jobs:
  setup-repo:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Add deployment environments
        run: |
          gh variable set REGION --body eu-central-1 --env prd
          gh variable set REGION --body eu-central-1 --env stg
          gh variable set AWS_AWS_CI_ROLE --body change-me --env prd
          gh variable set AWS_AWS_CI_ROLE --body change-me --env stg